spring:
  application:
    name: qianziw-order

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      retry:
        enabled: true

server:
  port: 8090

#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时
  ConnectTimeout: 5000

logging:
  level:
    com.qianziw.feignService.MemberFeignService: debug
